name: hensis-pnid-deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Define Variable for Build Step
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${REPO_NAME}:${GITHUB_SHA}"
          echo "Building image: $IMAGE_NAME"
          docker build -t "$IMAGE_NAME" .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV  # Export for next step

      - name: Push Docker image
        run: |
          echo "Pushing image: $IMAGE_NAME"
          docker push "$IMAGE_NAME"
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-24.04
    needs: build-and-push
    permissions:
      contents: read

    steps:
      - name: Define Image Name
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${REPO_NAME}:${GITHUB_SHA}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Deploy to remote server over SSH
        uses: appleboy/ssh-action@v0.1.8
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        with:
          host: ${{ secrets.REMOTE_SERVER }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/hensis_deployment/hensis_pnid
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            echo "Updating docker-compose.yml with new image: $IMAGE_NAME"
            yq -i ".services.hensis_pnid.image = \"$IMAGE_NAME\"" docker-compose.yml

            echo "Pulling and restarting services..."
            docker compose pull
            docker compose up -d
            
            echo "Running Alembic migrations..."
            docker compose exec hensis_pnid alembic upgrade head
            
            echo "Pruning unused Docker resources..."
            docker image prune -af --filter "until=24h" || true
            docker container prune -f || true
            docker volume prune -f || true

            echo "âœ… Deployment completed successfully."